module.exports = {
  products: [
    {
      _id: "1",
      name: "King Panel Bed",
      category: "Bedroom",
      image: "images/products/product-1.jpg",
      price: 585,
      countInStock: 4,
    },
    {
      _id: "2",
      name: "Super Kitchen",
      category: "Kitchen",
      image: "images/products/product-2.jpg",
      price: 3800,
      countInStock: 2,
    },
    {
      _id: "3",
      name: "Office Desk",
      category: "Office",
      image: "images/products/product-3.jpg",
      price: 250,
      countInStock: 8,
    },
    {
      _id: "4",
      name: "Color Chair",
      category: "Living Room",
      image: "images/products/product-4.jpg",
      price: 150,
      countInStock: 14,
    },
    {
      _id: "5",
      name: "Baby Room",
      category: "Baby Room",
      image: "images/products/product-5.jpg",
      price: 600,
      countInStock: 0,
    },
    {
      _id: "6",
      name: "Kitchen Table",
      category: "Kitchen",
      image: "images/products/product-6.jpg",
      price: 750,
      countInStock: 8,
    },
    {
      _id: "7",
      name: "Storage Boxes",
      category: "Living Room",
      image: "images/products/product-7.jpg",
      price: 150,
      countInStock: 6,
    },
    {
      _id: "8",
      name: "King Super Bed",
      category: "Bedroom",
      image: "images/products/product-8.jpg",
      price: 845,
      countInStock: 3,
    },
  ],
};
